name: build-docker-and-publish

on:
  release:
    types: [ released ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: docker/build-push-action@v1.1.0
        name: Build & push Docker image on Dockerhub
        with:
          tags: latest
          tag_with_ref: true
          repository: brandonfl/carbone-env-docker
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
